### ISSUE TITLE
Show Designer link broken

### ISSUE THREAD

**Issue by peternewman** [moritzvieli/show-designer-ofl-import#1]
I don't know if it's been made private/closed source or something? Although some compiled code is still on NPM obviously.

Also there's a translation error, which is why I was hunting for it, Add Effekt not Effect on the English version on the website.

**Comment by moritzvieli** [comment]
Indeed, the show-designer was private since the beginning, because I put a ton of effort into it and was not yet sure, how to proceed. I thought about making it public some time ago and just opened the repo right now to the public.

I'll check the translation error, thanks for reporting it!

**Comment by peternewman** [comment]
Awesome, this certainly wasn't a demand to make it open, just a query/thought. You could always just open source the translation if you wanted and leave the code to yourself. Although I'd imagine the NPM publish would mean people could rework the JS if not the TS even if it wasn't published.

If you're going to keep it open, it would probably be beneficial for people if you choose and add a licence to it.

**Comment by moritzvieli** [comment]
All good! Planned to open it anyways. And being a big fan of the OLA and your work, without this project would never have been possible, I think now the time is right, when even you are surfing around in those repos ;)

Yes, need to add a license and a proper readme. :)
